### ISSUE TITLE
illuminance broken in 0.85

### ISSUE THREAD

**Issue by danodemano** [pnbruckner/homeassistant-config#83]
Using both the sensor.dark_sky_icon and the weather.dark_sky do not work.  This was working in 0.84.6.

```
2019-01-10 13:45:44 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sensor.illuminance. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/loader.py", line 92, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/.homeassistant/custom_components/sensor/illuminance.py", line 19, in <module>
    from homeassistant.components.sensor.darksky import (
ImportError: cannot import name 'CONF_ATTRIBUTION'
2019-01-10 13:45:44 ERROR (MainThread) [homeassistant.loader] Unable to find component sensor.illuminance
```

**Comment by pnbruckner** [comment]
This was already noticed by @niemyjski, and he's already submitted a PR. This will be fixed by #82.

**Comment by danodemano** [comment]
My bad, didn't look at the PRs just the issues before submitting.  Thanks @pnbruckner !

**Comment by pnbruckner** [comment]
No problem. I usually leave issues opened until the PR is done, which will automatically close the issue. So I'll reopen. :)

**Comment by niemyjski** [comment]
My PR fixed the component from compiling but I'm still having an issue with the front end. I'm not 100% sure what's going on. It's like it's not finding the sensor (missing entity warning)

**Comment by danodemano** [comment]
@niemyjski - I implemented your fix directly and the component is showing on the front end as expected.  Is there anything you would like me to check?

![image](https://user-images.githubusercontent.com/1128744/51035798-33745980-1579-11e9-857f-47789e86843e.png)

**Comment by niemyjski** [comment]
Did something else change in 0.85 with the weather changes. I'm getting 

![image](https://user-images.githubusercontent.com/1020579/51117899-a4fc1400-17d4-11e9-815a-222d92ffedda.png)

and I know it's defined

**Comment by pnbruckner** [comment]
@niemyjski, where are you seeing that? Can you provide some more context? My code doesn't have an error message like that.

**Comment by niemyjski** [comment]
I have the sensor brought in to my setup and I can't get the sensor to show up. https://github.com/niemyjski/home-assistant

**Comment by niemyjski** [comment]
Doh, I think the sensor was deleted when I was moving around my config. I could have sworn I had it defined.
